owner: obrienafc
repo: status

sites:
  - name: CDN
    url: https://cdn.patrickob.tech
    icon: https://cdn.patrickob.tech/images/icons/content-delivery-network.png
  - name: Open WebUI
    url: https://chat.patrickob.tech
  - name: DomainsLocker
    url: https://domains.patrickob.tech
  - name: PDF Tools
    url: https://pdf.patrickob.tech
  - name: Memoes
    url: https://notes.patrickob.me
  - name: CS Phonetic
    url: https://csphonetic.patrickob.me
  - name: PLI SC Validator
    url: https://pligamevalidator.patrickob.me
  - name: Purelymail IMAP
    check: "tcp-ping"
    url: imap.purelymail.com
    port: 993
    icon: https://cdn.patrickob.tech/images/icons/purelymail.svg
  - name: Purelymail SMTP
    check: "tcp-ping"
    url: smtp.purelymail.com
    port: 465
    icon: https://cdn.patrickob.tech/images/icons/purelymail.svg
  - name: Purelymail POP3
    check: "tcp-ping"
    url: pop3.purelymail.com
    port: 995
    icon: https://cdn.patrickob.tech/images/icons/purelymail.svg

status-website:
  cname: status.patrickob.tech
  logoUrl: https://cdn.patrickob.tech/images/icons/status.png
  themeUrl: https://cdn.patrickob.tech/sites/status/css/custom.css
  name: Status Page
  introTitle: "Status page for self hosted services."
  favicon: https://cdn.patrickob.tech/images/icons/status.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
